name: hen_vision
description: Data Visualizer for poultry finance and operations.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

#============== PACKAGES ================#
dependencies:
  flutter:
    sdk: flutter

  #============== UITILITY PACKAGES ================#
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0

  #============== ICONS ================#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #============== STATE MANAGEMENT ================#
  get: ^4.6.5
  get_storage: ^2.1.1

#============== FLUTTER DEPENDENCIES ================#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
   uses-material-design: true

  #============== LOCAL ASSETS ================#
   assets:
     - assets/fonts/
     - assets/icons/
     - assets/images/
     - assets/logos/
     - assets/videos/

  #============== LOCAL FONTS ================#
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
